### ISSUE TITLE
re: Homebrew Updates

### ISSUE THREAD

**Issue by XianPalin** [matryer/bitbar-plugins#431] opened 2016-05-25 15:56 UTC
FAO: (@killercup)

One of the two plugins immediately fails with "Error: Another active Homebrew process is already in progress.".  I assume they are both hitting homebrew simultaneously which is / has become an issue with homebrew.

**Comment by kdeldycke** [comment] 2016-07-05 17:33
The root cause lie in running both [brew-updates.1h.sh](https://github.com/kdeldycke/bitbar-plugins/blob/master/Dev/Homebrew/brew-updates.1h.sh) and [homebrewcask.1d.sh](https://github.com/kdeldycke/bitbar-plugins/blob/master/Dev/Homebrew/homebrewcask.1d.sh) together. These two scripts must be mutually exclusive as running them concurrently impose a lock on the other.

To fix this issue, I created a new plugin which cover both Homebrew and Cask. For more details, see: https://github.com/matryer/bitbar-plugins/pull/466

**Comment by kdeldycke** [comment] 2016-07-06 06:42
My plugin has just been merged (see: #466).

To fix your issue, you should use: https://github.com/matryer/bitbar-plugins/blob/master/Dev/Homebrew/package_manager.7h.py

Now that there is a solution, I think it's safe to close this issue now.

**Closed** 2016-07-06 08:28 UTC
