### ISSUE TITLE
[Suggestion] Add global configuration files

### ISSUE THREAD

**Issue by oliviernt** [matryer/bitbar-plugins#220] opened 2016-02-10 08:07 UTC
It would be great to have a central place where we can store the plugin configuration instead of editing the plugin file itself.

For example in the jenkins-multiple-projects-status plugin, I need to change the USER, PASSWORD, etc... configs. This may lead to users wanting to make commits to a plugin to publish their configuration by mistake.

Instead we could introduce a config folder that is added to .gitignore where users will need to put their plugin configuration file.

This change would be non-breaking as old plugins would just keep the config in their plugin file while new plugins could benefit of the external config.

**Comment by keithamus** [comment] 2016-02-10 09:28
Hey @oliviernt thanks for the discussion. There's actually a really active discussion going on over at https://github.com/matryer/bitbar/issues/88, I'd recommend you have a little look at that, and provide some input if you have any.

I'll close this, because its a dupe of https://github.com/matryer/bitbar/issues/88

**Closed by keithamus** 2016-02-10 09:28 UTC

**Comment by oliviernt** [comment] 2016-02-10 09:36
Awesome, thank you! I wasn't aware of that discussion but I will chip in, in case I have something to add to it.
