### ISSUE TITLE
Passing command line parameters to program

### ISSUE THREAD

**Issue by konstantinkobs** [matryer/bitbar-plugins#31] opened 2016-01-08 09:37 UTC
Let's think about a plugin, that tracks the price of a product on Amazon. The user should be allowed to pass the link to the program, so it can scrape the site and show the price in BitBar. Or we want to create a plugin, that shows whether an update is available in your favorite RSS feeds.

For these purposes, it would be nice to have the possibility to pass arguments to your program without changing its code.

**Comment by keithamus** [comment] 2016-01-08 10:08
Hey @konstantinkobs there's a good discussion about this kind of stuff going on over at matryer/bitbar#88 which is probably a better place to have this discussions.

@matryer I'd say this issue should be closed - its a dupe of matryer/bitbar#88

**Closed** 2016-01-08 10:25 UTC
Labels: duplicate
